# Generated by Django 5.0.6 on 2024-06-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0003_menuitem_categoty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='categoty',
            new_name='category',
        ),
    ]
